// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using plt.Models.Model;

#nullable disable

namespace plt.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20251118134609_dlvs")]
    partial class dlvs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("plt.Models.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<int>("CountServicesDone")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LastDateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("PriceServices")
                        .HasColumnType("double precision");

                    b.Property<int>("ProfiId")
                        .HasColumnType("integer");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.HasIndex("LastDateId");

                    b.HasIndex("ProfiId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("plt.Models.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_type");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("plt.Models.Model.ServicesDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProfiId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("service_dates_pkey");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfiId");

                    b.ToTable("ServiceDates");
                });

            modelBuilder.Entity("plt.Models.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int?>("BasePrice")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("plt.Models.Model.Client", b =>
                {
                    b.HasOne("plt.Models.Model.ServicesDate", "LastDate")
                        .WithMany()
                        .HasForeignKey("LastDateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clients_service_dates_last_date_id");

                    b.HasOne("plt.Models.Model.User", "Profi")
                        .WithMany("Clients")
                        .HasForeignKey("ProfiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_profi_id");

                    b.Navigation("LastDate");

                    b.Navigation("Profi");
                });

            modelBuilder.Entity("plt.Models.Model.ServicesDate", b =>
                {
                    b.HasOne("plt.Models.Model.Client", "Client")
                        .WithMany("ServiceDates")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_dates_clients_client_id");

                    b.HasOne("plt.Models.Model.User", "Profi")
                        .WithMany("ServiceDates")
                        .HasForeignKey("ProfiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_dates_users_profi_id");

                    b.Navigation("Client");

                    b.Navigation("Profi");
                });

            modelBuilder.Entity("plt.Models.Model.User", b =>
                {
                    b.HasOne("plt.Models.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("plt.Models.Model.Client", b =>
                {
                    b.Navigation("ServiceDates");
                });

            modelBuilder.Entity("plt.Models.Model.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("ServiceDates");
                });
#pragma warning restore 612, 618
        }
    }
}
